version: '3.7'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=goomer
    volumes:
      - postgres_data:/bitnami/postgresql

  php:
    image: php:8.2-apache
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./services/products:/var/www/html
    depends_on:
      - mysql
    links:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_PASSWORD=docker
      - MYSQL_DATABASE=goomer
      - MYSQL_USER=mysql
    ports:
      - '3306:3306'

volumes:
  postgres_data: